--
--local key = KEYS[1]
--local threshold = tonumber(ARGV[1])
--local now = tonumber(ARGV[2])
--local windowSize = tonumber(ARGV[3])
--local beginTime = now - windowSize
--
--
--if redis.call("ZCARD", key) < threshold then
--    -- 把 score 和 member 都设置成 now
--    redis.call('ZADD', key, now, now)
--    redis.call('PEXPIRE', key, windowSize)
--    return "true"
--else
--    redis.call("ZREMRANGEBYSCORE", key, "-inf", beginTime)
--    if redis.call("ZCARD", key) < threshold then
--        -- 把 score 和 member 都设置成 now
--        redis.call('ZADD', key, now, now)
--        redis.call('PEXPIRE', key, windowSize)
--        return "true"
--    else
--        return "false"
--    end
--end

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangy.
--- DateTime: 2023/9/22 9:13
---
-- 1, 2, 3, 4, 5, 6, 7 这是你的元素
-- ZREMRANGEBYSCORE key1 0 6
-- 执行完之后 只剩 7

-- 限流对象
local key = KEYS[1]
-- 窗口大小
local window = tonumber(ARGV[1])
-- 阈值
local threshold = tonumber( ARGV[2])
local now = tonumber(ARGV[3])
-- 窗口的起始时间
local min = now - window

redis.call('ZREMRANGEBYSCORE', key, '-inf', min)
local cnt = redis.call('ZCOUNT', key, '-inf', '+inf')
-- local cnt = redis.call('ZCOUNT', key, min, '+inf')
if cnt >= threshold then
    -- 执行限流
    return "true"
else
    -- 把 score 和 member 都设置成 now
    redis.call('ZADD', key, now, now)
    redis.call('PEXPIRE', key, window)
    return "false"
end



